### ISSUE TITLE
example error

### ISSUE THREAD

**Issue by hsoni0303** [vmonaco/pohmm#2]
Error during run of example keystroke.py

Traceback (most recent call last):
  File "keystroke.py", line 217, in <module>
    verification(df)
  File "keystroke.py", line 179, in verification
    pohmm.fit_df(train)
  File "/home/hsoni0303/.local/lib/python3.6/site-packages/pohmm/pohmm.py", line 864, in fit_df
    obs = [df[df.columns.difference([pstate_col])][obs_cols].values for df in dfs]
  File "/home/hsoni0303/.local/lib/python3.6/site-packages/pohmm/pohmm.py", line 864, in <listcomp>
    obs = [df[df.columns.difference([pstate_col])][obs_cols].values for df in dfs]
  File "/home/hsoni0303/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 2133, in __getitem__
    return self._getitem_array(key)
  File "/home/hsoni0303/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 2177, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "/home/hsoni0303/.local/lib/python3.6/site-packages/pandas/core/indexing.py", line 1269, in _convert_to_indexer
    .format(mask=objarr[mask]))
KeyError: '[0 1] not in index'

**Comment by zcmail** [comment]
I had the same error.I solved it in this way:
replace the code 'df[df.columns.difference([pstate_col])][obs_cols].values' in pohmm.py with 'df[df.columns.difference([pstate_col])][['tau', 'duration']].values' when run keystroke.py.There are five.
